### ISSUE TITLE
Windows compatible?

### ISSUE THREAD

**Issue by FloridaStream** [JeroenED/Webcron#2]
Hi, this is windows compatible? 

can u provide a **demo login and pass**, i need to see some images, thank you @JeroenED

**Comment by JeroenED** [comment]
Hi @FloridaStream

The app itself should run fine on Windows as long as you have php installed. The only real adjustment to the installation process would be that you need to schedule the master script from the scheduled tasks instead of the crontab. The process should be similar.

For the demo login: I don't have one and I don't intend to make one. However, I can provide some screenshots from my installation of that would be OK to you?

**Comment by FloridaStream** [comment]
@JeroenED The images would be great, audible to know how it looks.
sorry the delay :)

**Comment by JeroenED** [comment]
Hi @FloridaStream 

On the link below you can find some screenshot I took of my installation. You'll probably see that design is not my best skill (nor it was the focus)

https://nextcloud.jeroened.be/index.php/s/PRBx4Rdr55ke2Mm
